# Site settings
title: Franziska Gündert
email: franziguendert@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Die deutsche Mezzosopranistin Franziska Gündert studierte an der 
  Musikhochschule Freiburg bei Prof. Sato-Schöllhorn und schloss 
  ihr Studium mit dem Master im Konzert- und Opernfach ab. Sie 
  vertiefte ihr Gesangsstudium in der Opernklasse am Conservatorium 
  of Music in Sydney bei Stephen Yalouris. Desweiteren gab sie 
  erfolgreiche Konzerte in Australien.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Franziska Gündert
email: franziguendert@gmail.com
facebook_username: 
soundcloud_username: franzisinger
youtube_channel: 
  # UCMIGKB8C52qv7NfuqU5ZoGg
address: []
  # Feel free to add more lines here 
telephone:  # +49 176 20 23 53 64
copyright: Franziska Gündert

collections:
  termine:
    output: true

# API settings
google_api_key:

# Build settings
markdown: kramdown